import Head from 'next/head'


export default function Home() {
  return (
    <>
      <Head>
        <title>Alex Rusovici portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className='container mx-auto px-4'>
          <p className='border'>
            Hello world v3
          </p>
        </div>
      </main>
    </>
  )
}
