import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import logo from './../../public/images/logo/logo.svg'


export default function Home() {
  return (
    <>
      <Head>
        <title>Alex Rusovici - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo/logo_icon.svg" />
      </Head>
      <main>
        <div className='container mx-auto px-4'>
          <Image src={logo} width={500} height={500} alt="Logo"></Image>
        </div>

        <div>
          <Link href='/LandingPage'><button>Welcome</button></Link>
        </div>
      </main>
    </>
  )
}
