import { Header } from '@/components/common/header';
import Head from 'next/head';

export default function LandingPage() {
  return (
    <>
      <Head>
        <title>Alex Rusovici - Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/images/logo/logo_icon.svg" />
      </Head>

      <header>
        <Header></Header>
      </header>
    </>
  );
}
